# It contains all the configs required in the project

data_source: http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

artifacts:
  ARTIFACTS_DIR: artifacts
  RAW_LOCAL_DIR: raw_local_dir
  RAW_LOCAL_FILE: data.csv
  SPLIT_DATA_DIR: split_data_dir
  TRAIN: train.csv
  TEST: test.csv
  MODEL_DIR: model_dir
  MODEL_NAME: model.pkl

scores: scores.json